### ISSUE TITLE
Problem with branch and path coverage (-ebpc)

### ISSUE THREAD

**Issue by syrm** [atoum/atoum#517] opened 2015-11-04 14:32 UTC
> tests\units\CCMBenchmark\Ting\Driver\Mysqli\Result...
> [U___________________________________________________________][1/1]
> => Test duration: 0.00 second.
> => Memory usage: 0.00 Mb.
> Total test duration: 0.00 second.
> Total test memory usage: 0.00 Mb.
> Running duration: 0.33 second.
> Failure (1 test, 0/1 method, 0 void method, 0 skipped method, 1 uncompleted method, 0 failure, 0 error, 0 exception)!
> There is 1 uncompleted method:
> => tests\units\CCMBenchmark\Ting\Driver\Mysqli\Result::testGetNumRows() with exit code -1:
> ==> output(0) ""

https://gist.github.com/oxman/011ac94858c7a1931843

Xdebug 2.4.0-dev

**Comment by jubianchi** [comment] 2015-11-04 14:35
Can you please try this : https://gist.github.com/oxman/011ac94858c7a1931843#gistcomment-1612402

**Comment by jubianchi** [comment] 2015-11-18 14:56
The root cause seems to be http://bugs.xdebug.org/view.php?id=1094

> it turns out that running xdebug_start_code_coverage(...) from within *any* function using the XDEBUG_CC_UNUSED setting causes my PHP to segfault

**Comment by jubianchi** [comment] 2016-05-14 07:59
closing this one as it it not directly related to branch and path coverage.

See #554.

**Closed** 2018-02-16 21:58 UTC
Labels: bug, feedback required
