### ISSUE TITLE
Fatal error when I run atoum using `.` directory for testing

### ISSUE THREAD

**Issue by shulard** [atoum/atoum#527] opened 2015-12-02 14:19 UTC
Hello,

I've worked on a Hoa project PR and I got a very strange error when running the atoum test suite.

The command used to run the test suite is :
```
vendor/bin/atoum --configurations vendor/hoa/test/.atoum.php --bootstrap-file vendor/hoa/test/.bootstrap.atoum.php --directories .
```

Specific configurations can be found here :
* configurations: https://github.com/hoaproject/Test/blob/master/.atoum.php
* boostrap: https://github.com/hoaproject/Test/blob/master/.bootstrap.atoum.php

This is the whole error message I get :

```
atoum is a simple, modern and intuitive PHP 5.3+ unit testing framework.
Copyright (c) 2010-2014, Frédéric Hardy.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Frédéric Hardy nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY FRÉDÉRIC HARDY AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL FRÉDÉRIC HARDY AND CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Fatal error: require_once(): Failed opening required 'phing/Task.php' (include_path='.:') in /Users/shulard/Sites/Forks/Hoa/Socket/vendor/atoum/atoum/resources/phing/AtoumTask.php on line 15
```

It seems that the constant `mageekguy\atoum\phing\task\path` in the file `vendor/atoum/atoum/resources/phing/AtoumTask.php` is not defined properly when I run the command using `.`. If I use `Test` as directory, the constant is defined...

I've tested on a Macbook Pro with different PHP versions installed from Homebrew :
* PHP 5.4.45
* PHP 5.5.30
* PHP 5.6.16
* PHP 7.0.0RC8

If you need more details about my config, just ask :smile: !

**Comment by jubianchi** [comment] 2015-12-02 19:31
This is not really a bug in atoum but more a wrong use of it :

* the `resources/phing/AtoumTask.php` file produces the error because it requires a file
* when using `--directories` you should point to a directory actually containing atoum tests or valid PHP files. 
* you configuration file should add the actual test directories and should not require you to provide them through CLI arguments

THe only thing I have to check here is why the license gets dumped to stdout.

**Comment by shulard** [comment] 2015-12-02 20:22
Ok I understand the problem here... I fill the issue because I though that a fatal is like an unmanaged error. Maybe a better message when no test suites are available can improve readability...

**Comment by jubianchi** [comment] 2015-12-03 07:50
@shulard when there is no test found, atoum displays something like "Error: no test found" the problem here is it can't conclude there is no test because of the fatal.

**Comment by shulard** [comment] 2015-12-03 10:53
Ok thanks for the details :smile:

**Comment by jubianchi** [comment] 2016-01-17 15:22
@shulard @Hywan I'm closing this issue as it is not a bug and changing this behavior makes no sense.

When using the `--directories` option user should take care of providing a directory actually containing test files. To find those tests, atoum has to `include` every file it finds in the tree (https://github.com/atoum/atoum/blob/master/classes/runner.php#L667-L670) and we know that including a text file will display its content.

atoum has an extension filter and wil only take care of files with the `.php` extension or those with no extension at all (https://github.com/atoum/atoum/blob/master/classes/iterators/filters/recursives/extension.php#L47), this is why the license gets displayed. Again, expected behavior.

Finally, the fatal is produced when atoum includes the phing task. Another expected behavior: to use this task, the user has to define a constant to let atoum know where the base `Task` class is (https://github.com/atoum/atoum/blob/master/resources/phing/AtoumTask.php#L10-L15)

**Closed by jubianchi** 2016-01-17 15:22 UTC

**Comment by Hywan** [comment] 2016-01-18 07:55
Thanks for the ping ;-).
