### ISSUE TITLE
Tests that do not execute on PHP7 with Xdebug

### ISSUE THREAD

**Issue by Spy-Seth** [atoum/atoum#554] opened 2016-01-15 13:36 UTC
I just found on weird behavior of atoum with PHP7 and Xdebug activated.

I've a tests suite that pass without Xdebug enabled. When I activate Xdebug some of my test do not pass. I've isolate one in a gist for the report: https://gist.github.com/Spy-Seth/da7b57653cb9ccba55f0. You could find the tested class, the test, and the tests output (with and without xdebug).

The weird part is that is not some random error triggered by some code, but tests method is juste not being executed: the `var_dump` result aren't show (and even some erroneous code are not executed `$a = 2/0;`.

<details>
<summary>

`Failure (1 test, 0/2 methods, 0 void method, 0 skipped method, 2 uncompleted methods, 0 failure, 0 error, 0 exception)!`
</summary>

```
> There are 2 uncompleted methods:
=> RedCross\tests\Units\Community\Domain\PredictiveUuidGenerator::test_the_predicted_uuids_should_be_returned() with exit code -1:
==> output(0) ""
=> RedCross\tests\Units\Community\Domain\PredictiveUuidGenerator::test_an_exception_should_be_throw_if_no_more_prediction_left() with exit code -1:
==> output(0) ""
```

</details>

I do not use any complex/dark PHP part that could explain this behavior. Someone have an idea?

**Comment by jubianchi** [comment] 2016-01-15 15:14
@Spy-Seth there are tons of problem with @xdebug on PHP7: it actually make PHP segfaults.

I can't really debug this as:

* it works on my machine,
* I don't have Windows

I'm following issues on the @xdebug bugtracker and also working on phpdbg integration which will hopefully solve those bugs.

**Comment by Spy-Seth** [comment] 2016-01-15 16:26
I understand that an issue like it is hard to debug. This code is extracted from a public POC that I made (https://github.com/Spy-Seth/crf-community/) maybe with the full test suits you could reproduce.

> I don't have Windows

Me neither. I'm running these tests on OSX :apple:

**Comment by jubianchi** [comment] 2016-05-14 07:59
So, the problem seems to be a bit different now with xDebug 2.4.0. But it's still making me crazy!

I've tracked down some segfaults in atoum's test suite, here is what I've found:

```php
<?php

$this
    ->given($this->newTestedInstance($generator = new asserter\generator()))
    // ...
; 
```

This snippet produces a segfault, but this one does not:

```php
<?php

$instance = $this->newTestedInstance($generator = new asserter\generator());

$this
    ->given($instance)
    // ...
; 
```

So I think there is an issue with how `given` and the like are managed by atoum, but:

```php
<?php

$given = function() { return $this->given(func_get_args()); };

$given($this->newTestedInstance($generator = new asserter\generator()))->...;
```

This does not produce any segfault.

So, the segfault seems to occur when we have something like the `$this-><keywork>($this-><keyword>)` pattern.

**Comment by vonglasow** [comment] 2016-05-16 07:40
@jubianchi I have a same kind of behavior here

```php
$this->object($this->newTestedInstance)->isTestedInstance();
$this->object($this->testedInstance->createService($mockServiceLocator))->isInstanceOf('Namespace\Classname');
```
Segfault
```php
$this->object($this->newTestedInstance)->isTestedInstance()
$service = $this->testedInstance->createService($mockServiceLocator);
$this->object($service)->isInstanceOf('Namespace\Classname');
```
Works

**Comment by Hywan** [comment] 2016-08-24 11:45
Is this issue happening only when code coverage is enabled? If yes, this is probably related to https://bugs.xdebug.org/view.php?id=1331.

Else, this can be related to https://bugs.xdebug.org/view.php?id=1322.

This is critical for the project because some companies are switching from atoum to PHPUnit because of this XDebug bug!

**Comment by Hywan** [comment] 2016-08-24 11:46
I asked helps to @derickr on Twitter, https://twitter.com/mnt_io/status/768414118038605824. And so here too 😄.

**Comment by derickr** [comment] 2016-08-24 12:53
I'm happy to help and fix this, but I need a short reproducible script: A complete case that I can run locally, and without any additional things to install or run.

**Comment by derickr** [comment] 2016-08-24 12:53
But also please try Xdebug 2.4.1 first.

**Comment by Hywan** [comment] 2016-08-24 12:57
Thank you. We are working on it.

**Comment by vonglasow** [comment] 2016-08-24 13:13
Crash report with Xdebug v2.5.0-dev (Xdebug commit 55fccbbcb8da0195bb9a7c332ea5364f58b9316b) compiled today

https://gist.github.com/vonglasow/f517595db6bccfc6c720810abaa6d093

I will try to make the same thing with Xdebug 2.4.1 in a day

**Comment by derickr** [comment] 2016-08-24 13:33
I don't need a crash report, I need a reproducible case. This Crash Report is not useful, so there is no need to spend time on making one for Xdebug 2.4.1.

**Comment by jubianchi** [comment] 2016-09-19 13:51
Thanks @derickr and @vonglasow!

@derickr you last commit [here](https://github.com/derickr/xdebug/commit/9c660551da07202f18928b2c749c121a8d410dd7) seems to fix the issues we have. I just compiled xDebug from your branch and ran the full atoum unit test suite : everything is OK!

@atoum/contributors if you want to test:

```sh
cd /tmp
git clone https://github.com/derickr/xdebug.git
cd xdebug
git checkout issue1331-code-coverage-segfault
phpize
./configure
make
```

Be sute to add the following lines to a `ini` file parsed by PHP:

```ini
zend_extension = /tmp/xdebug/modules/xdebug.so
xdebug.overload_var_dump = 0
```

You can now run the atoum test suite with code coverage and you should get no segfault!

```sh
cd /tmp
git clone https://github.com/atoum/atoum.git
cd /tmp/atoum
bin/atoum --test-it
```

**Comment by jubianchi** [comment] 2016-09-26 19:17
@derickr just to give you some updates about your recent fix in xdebug.

I managed to get PHP running with your patched xDebug (from https://github.com/derickr/xdebug/tree/issue1331-code-coverage-segfault) on travis CI (#632). Here are the builds:

* PHP 5.4: https://travis-ci.org/atoum/atoum/jobs/162867405
* PHP 5.5: https://travis-ci.org/atoum/atoum/jobs/162867408
* PHP 5.6: https://travis-ci.org/atoum/atoum/jobs/162867409
* PHP 7.0: https://travis-ci.org/atoum/atoum/jobs/162867410

Have a look at line 155/160 where e compile xDebug 2.4.1-dev and at line 1310/1330 where we get coverage results. 

We can see no build failing: no more segfault! I think everything is fine on the xDebug side. 

Can we expect a release of xDebug soon?

Thanks again @derickr!

**Comment by Hywan** [comment] 2016-09-27 07:19
Thanks @derickr!

**Comment by Spy-Seth** [comment] 2016-09-27 08:53
🎉

**Comment by Hywan** [comment] 2016-10-27 12:06
@derickr What's the next step then?

**Comment by derickr** [comment] 2016-10-27 15:04
Trying to sort one last 7.1 test failure right now... then I can make a new Xdebug (alpha) release.

**Comment by jubianchi** [comment] 2017-02-11 13:26
Should be fixed with the last xDebug release.

Thanks everyone!

**Comment by Hywan** [comment] 2017-02-11 13:26
:+1:

**Closed by jubianchi** 2017-02-11 13:26 UTC
Labels: bug, in progress, PHP7

**Comment by Spy-Seth** [comment] 2017-02-13 09:49
🎉
